### ISSUE TITLE
Error curl.

### ISSUE THREAD

**Issue by meugamer** [anigrab/wp-anigrab#1]
Hello I used your plugin in wordpress. But unfortunately, it has the following error:

 
 
===== ERROR RENDERING! ===== 

 CURL_EXEC() FAILED, HTTP CODE: 0 

===== powered by anigrab =====

**Comment by guangrei** [comment]
what type tag you use, id or url ?

**Comment by devz1107** [comment]
Gan perbarui donk error curl nya

**Comment by guangrei** [comment]
@devz1107 request curl berasal dari library jikan-me/jikan & animelist/mal-api, bisa di infokan bagaimana penggunaan tag nya sehingga tidak bekerja?>

**Comment by guangrei** [comment]
jika tidak sibuk pengembangan plugins akan dilanjutkan, untuk sekarang saya coba masih jalan dengan baik


tips:
- utamakan menggunakan [anigrab=id] daripada [anigrab=url]
- saat error pastikan sudah benar id/urlnya atau coba lagi setelah jeda beberapa saat

**Comment by guangrei** [comment]
the plugins has been updated, please open new issue if you found one.. thanks
